# Generated by Django 2.0.13 on 2019-09-09 22:45

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200)),
                ('ativo_categoria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=200)),
                ('longitude_estabelecimento', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitude_estabelecimento', models.DecimalField(decimal_places=16, max_digits=22)),
                ('logradouro_estabelecimento', models.CharField(max_length=200)),
                ('numero_logradouro_estabelecimento', models.CharField(max_length=200)),
                ('bairro_estabelecimento', models.CharField(max_length=200)),
                ('telefone_estabelecimento', models.CharField(max_length=14)),
                ('ativo_estabelecimento', models.BooleanField(default=True)),
                ('main_Picture_estabecimento', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='estabelecimentoImagens/')),
                ('picture01_estabecimento', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='estabelecimentoImagens/')),
                ('picture02_estabecimento', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='estabelecimentoImagens/')),
                ('picture03_estabecimento', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='estabelecimentoImagens/')),
                ('picture04_estabecimento', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='estabelecimentoImagens/')),
                ('categoria_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piripirifood.Categoria')),
            ],
        ),
    ]
