# Generated by Django 2.0.13 on 2019-09-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200)),
                ('ativo_categoria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=200)),
                ('ativo_estabelecimento', models.BooleanField(default=True)),
                ('categoria_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piripirifood.Categoria')),
            ],
        ),
    ]
