# Generated by Django 2.0.13 on 2019-09-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piripirifood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='latitude_estabelecimento',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='longitude_estabelecimento',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
    ]
