# Generated by Django 2.0.13 on 2019-09-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piripirifood', '0002_auto_20190904_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='bairro_estabelecimento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='logradouro_estabelecimento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='numero_logradouro_estabelecimento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='telefone_estabelecimento',
            field=models.CharField(default='', max_length=14),
        ),
    ]
