# Generated by Django 2.0.13 on 2019-09-05 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piripirifood', '0003_auto_20190904_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemEstabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagemEstab', models.CharField(max_length=200)),
                ('ativo_imagemEstab', models.BooleanField(default=True)),
                ('estabecimento_imagemEstab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piripirifood.Estabelecimento')),
            ],
        ),
    ]
